#!/bin/sh
saveTo=/var/www/html/bl/bl.rsc
now=$(date);

echo "# Generated by Joshaven Potter on $now" > $saveTo
echo "/ip firewall address-list" >> $saveTo

echo "#dshield"  >> $saveTo
wget -q -O - http://feeds.dshield.org/block.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.0\t/ { print "add list=blacklist address=" $1 "/24 timeout=1d comment=bl:DShield";}' >> $saveTo

echo "#spamhaus drop"  >> $saveTo
#echo "/ip firewall address-list" >> $saveTo
wget -q -O - https://www.spamhaus.org/drop/drop.txt | awk --posix '/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\// { print "add list=blacklist address=" $1 " timeout=1d comment=bl:SpamHaus";}' >> $saveTo

echo "#openbl"  >> $saveTo
#echo "/ip firewall address-list" >> $saveTo
wget -q -O - http://www.openbl.org/lists/base_7days.txt.gz | gunzip | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=blacklist address=" $1 " timeout=1d comment=bl:OpenBL";}' >> $saveTo

echo "#malc0de"  >> $saveTo
#echo "/ip firewall address-list" >> $saveTo
wget -q -O - http://malc0de.com/bl/IP_Blacklist.txt | awk --posix '/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/ { print "add list=blacklist address=" $1 "  timeout=1d comment=bl:malc0de";}' >> $saveTo

