server:
  interface: 127.0.0.153
  port: 5353
  do-not-query-localhost: no
  prefetch: yes
  qname-minimisation: no  # important for DNSBL
  cache-min-ttl: 60

  # allow DNSBL zones to work
  private-domain: "dnsbl.dennyhalim.com"
  private-domain: "dnsbl.dronebl.org"
  private-domain: "zen.spamhaus.org"
  private-domain: "xbl.spamhaus.org"
