#!/usr/bin/env python3
"""
Download IP/CIDR text lists and build one Exim iplsearch file.

Source file:
    /etc/exim4/light-gateway-blocklists

Format:
    # comments
    https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset
    https://example.net/another-list.txt

The parser accepts plain IPv4/IPv6 addresses and CIDRs embedded in ordinary
text-list lines. Output is written atomically.

For very large lists (hundreds of thousands/millions of networks), enforce
them in nftables/ipset instead of doing a linear iplsearch in every SMTP
connection.
"""

from __future__ import annotations

import ipaddress
import os
import re
import tempfile
import urllib.request
from pathlib import Path

SOURCES_FILE = Path("/etc/exim4/light-gateway-blocklists")
OUTPUT_FILE = Path("/var/lib/exim4/light-gateway/blocklist.ipl")

# Candidate tokens only; ipaddress performs the real validation.
TOKEN_RE = re.compile(r"(?<![0-9A-Fa-f:.])([0-9A-Fa-f:.]+(?:/\d{1,3})?)(?![0-9A-Fa-f:.])")


def read_sources() -> list[str]:
    urls: list[str] = []
    for raw in SOURCES_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if not line.startswith(("https://", "http://")):
            raise ValueError(f"unsupported source URL: {line}")
        urls.append(line)
    if not urls:
        raise ValueError(f"no sources configured in {SOURCES_FILE}")
    return urls


def fetch(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "exim-light-gateway/1.0"},
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"{url}: HTTP {response.status}")
        return response.read(64 * 1024 * 1024).decode("utf-8", errors="replace")


def parse_networks(text: str) -> set[ipaddress._BaseNetwork]:
    result: set[ipaddress._BaseNetwork] = set()

    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue

        for match in TOKEN_RE.finditer(line):
            token = match.group(1)
            try:
                network = ipaddress.ip_network(token, strict=False)
            except ValueError:
                continue

            # Never allow an accidental "block the whole Internet" entry.
            if network.prefixlen == 0:
                continue

            result.add(network)

    return result


def exim_line(network: ipaddress._BaseNetwork) -> str:
    value = str(network)
    if network.version == 6:
        return f'"{value}" blocklisted\n'
    return f"{value} blocklisted\n"


def sort_key(network: ipaddress._BaseNetwork):
    return (network.version, int(network.network_address), network.prefixlen)


def main() -> int:
    sources = read_sources()
    networks: set[ipaddress._BaseNetwork] = set()

    for url in sources:
        networks.update(parse_networks(fetch(url)))

    if not networks:
        raise RuntimeError("downloaded lists produced zero valid IP networks")

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    fd, tmp_name = tempfile.mkstemp(
        prefix=".blocklist.",
        dir=str(OUTPUT_FILE.parent),
        text=True,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as out:
            out.write("# generated by update-blocklists.py\n")
            for network in sorted(networks, key=sort_key):
                out.write(exim_line(network))
            out.flush()
            os.fsync(out.fileno())

        os.chmod(tmp_name, 0o644)
        os.replace(tmp_name, OUTPUT_FILE)
    finally:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass

    print(f"wrote {len(networks)} networks to {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
